import { ExecutionData } from "../../models/tiled-gameboy-tool-types"
import fs from 'fs'
import {sep} from 'path'
import objects from "../../features/objects";
import { getExecutionBankPragma } from "../../utils/execution.utils";

export default (executionData:ExecutionData)=>{

    /**
     * There is no banked specified if the user doesnt pass "autobanked", or an integer
     */
    const bankData = getExecutionBankPragma(executionData);


    const tileCount= executionData.mapHeight*executionData.mapWidth;

    const outputData = executionData.finalItems.map(x=>{return "0x"+(x.index)})
    const outputDataAttributes = outputData.map(x=>"0")

    const exportCContent = `
${bankData}

//AUTOGENERATED FILE FROM tiled-gameboy-tool

#include <stdint.h>
#include <gbdk/platform.h>

BANKREF(${executionData.identifier})

const unsigned char ${executionData.identifier}_map[${tileCount}] = {
	${outputData.join(",")}
};

const unsigned char ${executionData.identifier}_map_attributes[${tileCount}] = {
	${outputDataAttributes.join(",")}
};

    
`;

    const exportHContent = `
//AUTOGENERATED FILE FROM tiled-gameboy-tool

#include <stdint.h>
#include <gbdk/platform.h>

#define ${executionData.identifier}_TILE_COUNT ${tileCount}

const unsigned char ${executionData.identifier}_map[${tileCount}];
const unsigned char ${executionData.identifier}_map_attributes[${tileCount}] ;

    
`;

    fs.writeFileSync(`${executionData.outputDirectory+sep+executionData.identifier}.c`,exportCContent)
    fs.writeFileSync(`${executionData.outputDirectory+sep+executionData.identifier}.h`,exportHContent)
}