import { ExecutionData } from "../models/tiled-gameboy-tool-types"
import fs from 'fs'

export default (executionData:ExecutionData)=>{

    const id = executionData.identifier;
    const tileCount= executionData.mapHeight*executionData.mapWidth;

    const outputData = executionData.finalItems.map(x=>"0x"+x.index.toString(16))
    const outputDataAttributes = outputData.map(x=>"0")

    const exportContent = `
    
    #pragma bank 255

//AUTOGENERATED FILE FROM tiled-gameboy-tool

#include <stdint.h>
#include <gbdk/platform.h>

BANKREF(${id})


const unsigned char ${id}_map[${tileCount}] = {
	${outputData.join(",")}
};

const unsigned char ${id}_map_attributes[${tileCount}] = {
	${outputDataAttributes.join(",")}
};

    
    `

    fs.writeFileSync('output-gbdk.c',exportContent)
}