import { ExecutionData, ExportListItem } from "../../models/tiled-gameboy-tool-types"
import {sep} from 'path'

const getRGBDSExportContents = (executionData:ExecutionData)=>{

    var rows:string[][] = [];

    for(var i=0;i<executionData.finalItems.length;i++){

        var row = Math.floor(i/executionData.mapWidth);

        if(row>=rows.length)rows.push([])

        rows[row].push("$"+executionData.finalItems[i].index.toString(16))
    }

    var mappedRows = rows.map(x=>"\tDB "+x.join(",").toUpperCase())
    
    const writeContent = `
;AUTOGENERATED FILE FROM tiled-gameboy-tool

SECTION "${executionData.identifier}TilemapSection", ROM0

${executionData.identifier}_Map::
${mappedRows.join("\n")}
${executionData.identifier}_MapEnd::
    
    `
    return writeContent;
}


export const getRGBDSExport = (executionData:ExecutionData):ExportListItem[]=>{
    return [
        {
            file: `${executionData.outputDirectory+sep+executionData.identifier}.asm`,
            contents: getRGBDSExportContents(executionData)
        }
    ]
}
