import { ExecutionData, ExportListItem } from "../../models/tiled-gameboy-tool-types"
import {sep} from 'path'
import { splitArrayIntoRows } from "../array.utils";

const mapToTabbedByteRow = (x:string[])=>"\tDB "+x.map(x=>"$"+Number(x).toString(16)).join(",").toUpperCase()

const getRGBDSExportContents = (executionData:ExecutionData)=>{
    var mappedRows = splitArrayIntoRows(executionData.finalItems,executionData.mapWidth)
    var mappedRowsAttributes = splitArrayIntoRows(executionData.finalItems,executionData.mapWidth)
    
    const writeContent = `
;AUTOGENERATED FILE FROM tiled-gameboy-tool

SECTION "${executionData.identifier}Section", ROM0

${executionData.identifier}_Map::
${mappedRows.map(x=>"\tDB "+x.map(y=>"$"+y.index.toString(16)).join(", ")).join("\n")}
${executionData.identifier}_MapEnd::

${executionData.identifier}_Map_Attributes::
${mappedRowsAttributes.map(x=>"\tDB "+x.map(y=>"$"+y.index.toString(16)).join(", ")).join("\n")}
${executionData.identifier}_Map_AttributesEnd::
    
    `
    return writeContent;
}


export const getRGBDSExport = (executionData:ExecutionData,exportList: ExportListItem[] ):void=>{
    exportList[0].contents.push(getRGBDSExportContents(executionData))
}
