name: Default Github Action

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |

        # make sure pkg is installed
        # pkg can be found here: https://www.npmjs.com/pkg
        npm install -g pkg
        npm install

        # skip the integration tests, and perform unit tests
        npm test -- --testPathIgnorePatterns /test/integration/ --testPathIgnorePatterns /build/ --testPathIgnorePatterns /node_modules/

        # Make sure we have 'dist' folders for our versions
        mkdir dist
        mkdir dist/windows
        mkdir dist/linux
        mkdir dist/macos

        # Build the code and and package the application
        npm run build:package

        # skip the unit tests, and perform integration tests
        # integration test omitted for now
        # GBDK_HOME=gbdk-linux64/gbdk/
        # npm test -- --testPathIgnorePatterns /src/ --testPathIgnorePatterns /build/ --testPathIgnorePatterns /node_modules/